apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-backend
  namespace: sentiment-mlops
  labels:
    app: ml-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-backend
  template:
    metadata:
      labels:
        app: ml-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: ml-backend
        image: sentiment-ml-backend:latest
        imagePullPolicy: Never # Set to Never for minikube local image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ml-backend-svc
  namespace: sentiment-mlops
  labels:
    app: ml-backend
spec:
  type: NodePort
  selector:
    app: ml-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
